services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres17
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_bank
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]
volumes:
  postgres_data:
